### ISSUE TITLE
opened file is not clearly distinguishable 

### ISSUE THREAD

**Issue by realamirhe** [ziterz/codesandbox-black-theme#2]
![image](https://user-images.githubusercontent.com/23579958/144249823-c94358b0-2c48-4058-9a5f-8cb20ff26f6c.png)
![image](https://user-images.githubusercontent.com/23579958/144249901-56d76377-14dd-4339-af1d-81f8f8c5d223.png)

In the first image first file is open to be edited and in the second one the 2nd.
Is there a way to update the theme to make more focus on open file?
@ziterz

**Comment by NusryNizam** [comment]
Yeah, i just came here to make an issue too. But found this instead. Love this theme. A fix would be appreciated.
It's hard to distinguish which tab is active.
![image](https://user-images.githubusercontent.com/24385617/147863994-21baaf2a-073e-4ad8-bf90-93413fca6a6e.png)

**Comment by realamirhe** [comment]
it seems it is not maintained anymore, If you are okay we can fork and continue patches on our own. @NusryNizam 

The theme actually can be exactly generated  with `>Developer: Generate Color Theme From Current Settings`

**Comment by NusryNizam** [comment]
Yeah, sure!
> we can fork and continue patches

**Comment by ziadyjo** [comment]
hai @amirHossein-Ebrahimi and @NusryNizam sorry for the issue, i'll try to fix ttyl!

**Comment by ziadyjo** [comment]
in this case i'll add underline to make focus on the active tab, but I hope this doesn't change the design concept

**Comment by ziadyjo** [comment]
pls update to 1.2.5 version, thanks!

**Comment by NusryNizam** [comment]
@ziterz Thanks
